# Generated by Django 4.0.5 on 2022-07-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppealModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО отправителя')),
                ('email', models.CharField(max_length=255, verbose_name='Email отправителя')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('file', models.FileField(blank=True, upload_to='index_enbvu/obrasenie_files/')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Обращение к руководителю (письма водопользователей)',
                'ordering': ['-date_created'],
            },
        ),
    ]
