# Generated by Django 4.0.5 on 2022-07-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealmodel',
            name='get_approval',
            field=models.BooleanField(default=1, verbose_name='Согласие на обработку данных'),
            preserve_default=False,
        ),
    ]
