# Generated by Django 4.0.5 on 2022-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_appealmodel_get_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealmodel',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='appealmodel',
            name='file',
            field=models.FileField(blank=True, upload_to='index_enbvu/obrashenie_files/', verbose_name='Файл'),
        ),
    ]
