# Generated by Django 4.0.5 on 2022-07-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0003_alter_appealmodel_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appealmodel',
            options={'ordering': ['-date_created'], 'verbose_name': 'Сообщения', 'verbose_name_plural': '1. Обращение к руководителю (письма водопользователей)'},
        ),
    ]
