# Generated by Django 4.0.5 on 2022-08-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0091_alter_content_options'),
        ('appeal', '0004_alter_appealmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=555, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('mode_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.modepage', verbose_name='Вид контекста')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': '1. Добавить Контент',
                'ordering': ['-date_change'],
            },
        ),
        migrations.CreateModel(
            name='UnMenuAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ListFileAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст (пояснение к файлу)')),
                ('content_appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.contentappeal')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Добавить список файлов',
            },
        ),
        migrations.CreateModel(
            name='FileAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название файла')),
                ('file', models.FileField(blank=True, upload_to='appeal/files', verbose_name='Файл')),
                ('content_appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.contentappeal')),
                ('list_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.listfileappeal', verbose_name='Пояснение к файлу')),
                ('picture_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.picturefile', verbose_name='Расширение файла')),
            ],
            options={
                'verbose_name': 'Файл',
            },
        ),
        migrations.AddField(
            model_name='contentappeal',
            name='un_menu_appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.unmenuappeal', verbose_name='Подпункт меню'),
        ),
    ]
