# Generated by Django 4.0.5 on 2022-08-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0005_contentappeal_unmenuappeal_listfileappeal_fileappeal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentappeal',
            options={'ordering': ['-date_change'], 'verbose_name': 'Контент', 'verbose_name_plural': '2. Добавить Контент'},
        ),
    ]
