# Generated by Django 4.0.5 on 2022-08-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0006_alter_contentappeal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appealmodel',
            options={'ordering': ['-date_created'], 'verbose_name': 'Сообщения', 'verbose_name_plural': '2. Обращение к руководителю (письма водопользователей)'},
        ),
        migrations.AlterModelOptions(
            name='contentappeal',
            options={'ordering': ['-date_change'], 'verbose_name': 'Контент', 'verbose_name_plural': '1. Добавить Контент'},
        ),
    ]
