# Generated by Django 4.0.4 on 2022-06-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.TextField(max_length=300, verbose_name='URL'),
        ),
    ]
