# Generated by Django 4.0.4 on 2022-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0004_alter_menu_title_alter_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст новости')),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='Фото')),
                ('save_pdf', models.FileField(blank=True, upload_to='files_pdf/', verbose_name='Файл PDF')),
                ('document_other', models.FileField(blank=True, upload_to='files', verbose_name='Все файлы')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
    ]
