# Generated by Django 4.0.4 on 2022-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='index_enbvu/images/', verbose_name='Фото'),
        ),
    ]
