# Generated by Django 4.0.5 on 2022-06-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0008_alter_menu_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='document_other',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Все файлы'),
        ),
    ]
