# Generated by Django 4.0.5 on 2022-06-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0010_alter_news_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_update',
            field=models.DateTimeField(verbose_name='Дата изменения'),
        ),
    ]
