# Generated by Django 4.0.5 on 2022-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0011_alter_news_date_create_alter_news_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
