# Generated by Django 4.0.5 on 2022-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0012_alter_news_time_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='index_enbvu', verbose_name='Фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
    ]
