# Generated by Django 4.0.5 on 2022-06-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0013_newsimage_remove_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='index_enbvu.news', verbose_name='Новость'),
            preserve_default=False,
        ),
    ]
