# Generated by Django 4.0.5 on 2022-06-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0016_remove_news_document_other_remove_news_save_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='files',
        ),
    ]
