# Generated by Django 4.0.5 on 2022-06-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0018_newsimage_css'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
