# Generated by Django 4.0.5 on 2022-06-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0020_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('url', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index_enbvu.menu', verbose_name='Пункт меню')),
            ],
            options={
                'verbose_name': 'Подпункт меню',
                'verbose_name_plural': 'Подпункт Меню',
                'ordering': ['id'],
            },
        ),
    ]
