# Generated by Django 4.0.5 on 2022-06-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0022_alter_unmenu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='index_enbvu/photo_link', verbose_name='Картинка')),
                ('url', models.CharField(max_length=300, verbose_name='Ссылка на ресурс')),
            ],
            options={
                'verbose_name': 'Ссылку на внешний ресурс',
                'verbose_name_plural': 'Ссылки на внешний ресурс',
            },
        ),
    ]
