# Generated by Django 4.0.5 on 2022-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0024_veteran'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteran',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
