# Generated by Django 4.0.5 on 2022-07-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0025_veteran_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteran',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
