# Generated by Django 4.0.5 on 2022-07-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0026_alter_veteran_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veteran',
        ),
    ]
