# Generated by Django 4.0.5 on 2022-07-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0027_delete_veteran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='index_enbvu/photo_veteran', verbose_name='Фото')),
                ('date_created', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Фото ветерана',
                'verbose_name_plural': 'Бессмертный полк',
            },
        ),
    ]
