# Generated by Django 4.0.4 on 2022-07-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0030_veteranlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veteranlist',
            name='slug',
        ),
    ]
