# Generated by Django 4.0.5 on 2022-07-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0031_remove_veteranlist_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirVody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='index_enbvu/mir_vody/%Y', verbose_name='Фото')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Мир воды',
            },
        ),
    ]
