# Generated by Django 4.0.5 on 2022-07-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0032_mirvody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mirvody',
            name='slug',
        ),
        migrations.AddField(
            model_name='mirvody',
            name='link_year',
            field=models.IntegerField(default=1, verbose_name='Ссылка на год'),
            preserve_default=False,
        ),
    ]
