# Generated by Django 4.0.5 on 2022-07-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0033_remove_mirvody_slug_mirvody_link_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirVodyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='index_enbvu/mir_vody/%Y', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='MirVodyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_year', models.CharField(max_length=200, verbose_name='Год конкурса')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Год конкурса',
                'verbose_name_plural': 'Мир воды',
            },
        ),
        migrations.DeleteModel(
            name='MirVody',
        ),
        migrations.AddField(
            model_name='mirvodyimage',
            name='mir_vody_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index_enbvu.mirvodyyear', verbose_name='Рисунок'),
        ),
    ]
