# Generated by Django 4.0.5 on 2022-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0034_mirvodyimage_mirvodyyear_delete_mirvody_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mirvodyyear',
            name='link_year',
        ),
        migrations.AddField(
            model_name='mirvodyyear',
            name='slug',
            field=models.SlugField(default=1, max_length=200, verbose_name='Год конкурса'),
            preserve_default=False,
        ),
    ]
