# Generated by Django 4.0.4 on 2022-07-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0035_remove_mirvodyyear_link_year_mirvodyyear_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfilepdf',
            name='pdf',
            field=models.FileField(blank=True, upload_to='index_enbvu/news/files_pdf/', verbose_name='Файл PDF'),
        ),
        migrations.AlterField(
            model_name='newsfiles',
            name='file',
            field=models.FileField(blank=True, upload_to='index_enbvu/news/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='index_enbvu/news/image_news/', verbose_name='Фото'),
        ),
    ]
