# Generated by Django 4.0.5 on 2022-07-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0037_alter_mirvodyimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfilepdf',
            name='pdf',
            field=models.FileField(blank=True, upload_to='index_enbvu/news/files_pdf/', verbose_name='Файл PDF (Значок "PDF")'),
        ),
        migrations.AlterField(
            model_name='newsfiles',
            name='file',
            field=models.FileField(blank=True, upload_to='index_enbvu/news/files/', verbose_name='Файл ("Желтая папка")'),
        ),
    ]
