# Generated by Django 4.0.5 on 2022-07-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0038_alter_newsfilepdf_pdf_alter_newsfiles_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': '1. Меню'},
        ),
        migrations.AlterModelOptions(
            name='mirvodyyear',
            options={'verbose_name': 'Год конкурса', 'verbose_name_plural': '6. Мир воды'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_create'], 'verbose_name': 'Новость', 'verbose_name_plural': '3. Новости'},
        ),
        migrations.AlterModelOptions(
            name='photolink',
            options={'verbose_name': 'Ссылку на внешний ресурс', 'verbose_name_plural': '4. Ссылки на внешний ресурс'},
        ),
        migrations.AlterModelOptions(
            name='unmenu',
            options={'ordering': ['id'], 'verbose_name': 'Меню ПодПункт', 'verbose_name_plural': '2. Меню ПодПункты'},
        ),
        migrations.AlterModelOptions(
            name='veteranlist',
            options={'verbose_name': 'Фото ветерана', 'verbose_name_plural': '5. Бессмертный полк'},
        ),
    ]
