# Generated by Django 4.0.5 on 2022-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0039_alter_menu_options_alter_mirvodyyear_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mirvodyimage',
            options={'verbose_name': 'Фото, картинки', 'verbose_name_plural': 'Добавить Фото'},
        ),
        migrations.AlterModelOptions(
            name='newsfilepdf',
            options={'verbose_name': 'Файл PDF', 'verbose_name_plural': 'Добавить Файл PDF (Значок "PDF")'},
        ),
        migrations.AlterModelOptions(
            name='newsfiles',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Добавить Файл PDF (Значок "Папка")'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Фото, картинки', 'verbose_name_plural': 'Добавить Фото'},
        ),
        migrations.AlterField(
            model_name='newsfilepdf',
            name='pdf',
            field=models.FileField(blank=True, upload_to='index_enbvu/news/files_pdf/', verbose_name='Файл PDF '),
        ),
    ]
