# Generated by Django 4.0.5 on 2022-08-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0040_alter_mirvodyimage_options_alter_newsfilepdf_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfiles',
            name='news_file',
        ),
        migrations.DeleteModel(
            name='NewsFilePDF',
        ),
        migrations.DeleteModel(
            name='NewsFiles',
        ),
    ]
