# Generated by Django 4.0.5 on 2022-08-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0042_baseimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseimage',
            options={'verbose_name': 'Фото, картинки', 'verbose_name_plural': 'Добавить Фото'},
        ),
    ]
