# Generated by Django 4.0.5 on 2022-08-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0043_alter_baseimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hot',
            field=models.BooleanField(default=False, verbose_name='Горячая новость'),
        ),
    ]
