# Generated by Django 4.0.5 on 2022-08-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0044_news_hot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseimage',
            options={'verbose_name': 'Фото, картинки', 'verbose_name_plural': '5. Добавить Фото'},
        ),
        migrations.AlterModelOptions(
            name='mirvodyyear',
            options={'verbose_name': 'Год конкурса', 'verbose_name_plural': '3. Мир воды'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_create'], 'verbose_name': 'Новость', 'verbose_name_plural': '1. Новости'},
        ),
        migrations.AlterModelOptions(
            name='photolink',
            options={'verbose_name': 'Ссылку на внешний ресурс', 'verbose_name_plural': '2. Ссылки на внешний ресурс'},
        ),
        migrations.AlterModelOptions(
            name='veteranlist',
            options={'verbose_name': 'Фото ветерана', 'verbose_name_plural': '4. Бессмертный полк'},
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
