# Generated by Django 4.0.5 on 2022-08-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_enbvu', '0045_alter_baseimage_options_alter_mirvodyyear_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseImage',
        ),
    ]
