# Generated by Django 4.0.5 on 2022-08-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealAntiCorruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тема сообщения')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('file', models.FileField(blank=True, upload_to='corruption/appeal_cor/files', verbose_name='Прикрепленный файл')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Соощения о коррупции',
                'ordering': ['-date_created'],
            },
        ),
    ]
