# Generated by Django 4.0.5 on 2022-08-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0002_appealanticorruption'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.IntegerField(default=0, verbose_name='Высокий уровень')),
                ('average', models.IntegerField(default=0, verbose_name='Средний уровень')),
                ('short', models.IntegerField(default=0, verbose_name='Низкий уровень')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Оценка работы по противодействию коррупции',
                'ordering': ['-date_created'],
            },
        ),
    ]
