# Generated by Django 4.0.5 on 2022-08-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0003_ratingwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingwork',
            options={},
        ),
        migrations.RemoveField(
            model_name='ratingwork',
            name='date_created',
        ),
        migrations.AddField(
            model_name='ratingwork',
            name='type',
            field=models.CharField(choices=[('high', 'HIGH'), ('average', 'AVERAGE'), ('short', 'SHORT')], default='high', max_length=255),
        ),
        migrations.AlterField(
            model_name='ratingwork',
            name='average',
            field=models.BooleanField(default=False, verbose_name='Средний уровень'),
        ),
        migrations.AlterField(
            model_name='ratingwork',
            name='high',
            field=models.BooleanField(default=False, verbose_name='Высокий уровень'),
        ),
        migrations.AlterField(
            model_name='ratingwork',
            name='short',
            field=models.BooleanField(default=False, verbose_name='Низкий уровень'),
        ),
    ]
