# Generated by Django 4.0.5 on 2022-08-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0006_ratingwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appealanticorruption',
            options={'ordering': ['-date_created'], 'verbose_name': 'Соощения о коррупции', 'verbose_name_plural': '2. Соощения о коррупции'},
        ),
    ]
