# Generated by Django 4.0.5 on 2022-07-28 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deyatelnost', '0002_contentdeyatelnost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFileDeyatelnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст (пояснение к файлу)')),
                ('content_deyatelnost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deyatelnost.contentdeyatelnost')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Добавить список файлов',
            },
        ),
    ]
