# Generated by Django 4.0.5 on 2022-07-28 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0088_file_picture_file_alter_file_name'),
        ('deyatelnost', '0003_listfiledeyatelnost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDeyatelnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название файла')),
                ('file', models.FileField(blank=True, upload_to='deyatelnost/files', verbose_name='Файл')),
                ('content_deyatelnost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deyatelnost.contentdeyatelnost')),
                ('list_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deyatelnost.listfiledeyatelnost', verbose_name='Пояснение к файлу')),
                ('picture_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.picturefile', verbose_name='Расширение файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Добавить файлы',
            },
        ),
    ]
