# Generated by Django 4.0.5 on 2022-07-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deyatelnost', '0004_filedeyatelnost'),
    ]

    operations = [
        migrations.CreateModel(
            name='VodHoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservoir_s_shush', models.CharField(max_length=355, verbose_name='Саяно-Шушенское водохранилище')),
                ('reservoir_mainsk', models.CharField(max_length=355, verbose_name='Майнское водохранилище')),
                ('reservoir_kras', models.CharField(max_length=355, verbose_name='Красноярское водохранилище')),
                ('reservoir_irk', models.CharField(max_length=355, verbose_name='Иркутское водохранилище')),
                ('reservoir_bratsk', models.CharField(max_length=355, verbose_name='Братское водохранилище')),
                ('reservoir_us_il', models.CharField(max_length=355, verbose_name='Усть-Илимское водохранилище')),
                ('reservoir_boguch', models.CharField(max_length=355, verbose_name='Богучанское водохранилище')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Водохозяйственная обстановка',
                'verbose_name_plural': 'Разместить водохозяйственную обстановку',
            },
        ),
        migrations.AlterModelOptions(
            name='filedeyatelnost',
            options={'verbose_name': 'Файл'},
        ),
        migrations.AlterField(
            model_name='contentdeyatelnost',
            name='title',
            field=models.CharField(blank=True, max_length=455, verbose_name='Заголовок'),
        ),
    ]
