# Generated by Django 4.0.5 on 2022-07-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deyatelnost', '0005_vodhoz_alter_filedeyatelnost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vodhoz',
            options={'verbose_name': 'Водохозяйственную обстановку', 'verbose_name_plural': 'Водохозяйственная обстановка'},
        ),
        migrations.RemoveField(
            model_name='vodhoz',
            name='reservoir_boguch',
        ),
        migrations.RemoveField(
            model_name='vodhoz',
            name='reservoir_bratsk',
        ),
        migrations.RemoveField(
            model_name='vodhoz',
            name='reservoir_irk',
        ),
        migrations.RemoveField(
            model_name='vodhoz',
            name='reservoir_kras',
        ),
        migrations.RemoveField(
            model_name='vodhoz',
            name='reservoir_mainsk',
        ),
        migrations.RemoveField(
            model_name='vodhoz',
            name='reservoir_s_shush',
        ),
        migrations.RemoveField(
            model_name='vodhoz',
            name='reservoir_us_il',
        ),
        migrations.AddField(
            model_name='vodhoz',
            name='reservoir',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
