# Generated by Django 4.0.5 on 2022-07-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deyatelnost', '0006_alter_vodhoz_options_remove_vodhoz_reservoir_boguch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservoir_s_shush', models.CharField(max_length=355, verbose_name='Саяно-Шушенское водохранилище')),
                ('reservoir_mainsk', models.CharField(max_length=355, verbose_name='Майнское водохранилище')),
                ('reservoir_kras', models.CharField(max_length=355, verbose_name='Красноярское водохранилище')),
                ('reservoir_irk', models.CharField(max_length=355, verbose_name='Иркутское водохранилище')),
                ('reservoir_bratsk', models.CharField(max_length=355, verbose_name='Братское водохранилище')),
                ('reservoir_us_il', models.CharField(max_length=355, verbose_name='Усть-Илимское водохранилище')),
                ('reservoir_boguch', models.CharField(max_length=355, verbose_name='Богучанское водохранилище')),
            ],
        ),
        migrations.CreateModel(
            name='ShowVodHozObst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.DeleteModel(
            name='VodHoz',
        ),
    ]
