# Generated by Django 4.0.5 on 2022-07-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deyatelnost', '0007_reservoir_showvodhozobst_delete_vodhoz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservoir',
            name='reservoir_boguch',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='reservoir_bratsk',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='reservoir_irk',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='reservoir_kras',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='reservoir_mainsk',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='reservoir_s_shush',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='reservoir_us_il',
        ),
        migrations.AddField(
            model_name='reservoir',
            name='reservoir',
            field=models.CharField(default=1, max_length=355, verbose_name='Водохранилище'),
            preserve_default=False,
        ),
    ]
