# Generated by Django 4.0.5 on 2022-07-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deyatelnost', '0009_delete_reservoir_delete_showvodhozobst'),
    ]

    operations = [
        migrations.CreateModel(
            name='VodHoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayno_sush', models.TextField(verbose_name='Саяно-Шушенское водохранилище')),
                ('maiynskoe', models.TextField(verbose_name='Майнское водохранилище')),
                ('kras', models.TextField(verbose_name='Красноярское водохранилище')),
                ('irk', models.TextField(verbose_name='Иркутское водохранилище')),
                ('bratsk', models.TextField(verbose_name='Братское водохранилище')),
                ('ust_ilim', models.TextField(verbose_name='Усть-Илимское водохранилище')),
                ('boguch', models.TextField(verbose_name='Богучанское водохранилище')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Водохозяйственныую обстановку',
                'verbose_name_plural': 'Водохозяйственная обстановка',
            },
        ),
    ]
