# Generated by Django 4.0.5 on 2022-07-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deyatelnost', '0010_vodhoz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vodhoz',
            options={'ordering': ['-date_created'], 'verbose_name': 'Водохозяйственныую обстановку', 'verbose_name_plural': 'Водохозяйственная обстановка'},
        ),
        migrations.AlterField(
            model_name='vodhoz',
            name='boguch',
            field=models.CharField(max_length=355, verbose_name='Богучанское водохранилище'),
        ),
        migrations.AlterField(
            model_name='vodhoz',
            name='bratsk',
            field=models.CharField(max_length=355, verbose_name='Братское водохранилище'),
        ),
        migrations.AlterField(
            model_name='vodhoz',
            name='irk',
            field=models.CharField(max_length=355, verbose_name='Иркутское водохранилище'),
        ),
        migrations.AlterField(
            model_name='vodhoz',
            name='kras',
            field=models.CharField(max_length=355, verbose_name='Красноярское водохранилище'),
        ),
        migrations.AlterField(
            model_name='vodhoz',
            name='maiynskoe',
            field=models.CharField(max_length=355, verbose_name='Майнское водохранилище'),
        ),
        migrations.AlterField(
            model_name='vodhoz',
            name='sayno_sush',
            field=models.CharField(max_length=355, verbose_name='Саяно-Шушенское водохранилище'),
        ),
        migrations.AlterField(
            model_name='vodhoz',
            name='ust_ilim',
            field=models.CharField(max_length=355, verbose_name='Усть-Илимское водохранилище'),
        ),
    ]
