# Generated by Django 4.0.5 on 2022-08-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deyatelnost', '0011_alter_vodhoz_options_alter_vodhoz_boguch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регион',
            },
        ),
        migrations.AlterModelOptions(
            name='contentdeyatelnost',
            options={'ordering': ['-date_change'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Добавить Контент'},
        ),
        migrations.AlterField(
            model_name='contentdeyatelnost',
            name='title',
            field=models.CharField(blank=True, max_length=555, verbose_name='Заголовок'),
        ),
    ]
