# Generated by Django 4.0.5 on 2022-08-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0090_alter_content_options'),
        ('deyatelnost', '0013_prikazozonepodtop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFilePrikazOZonePodtop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст (пояснение к файлу)')),
                ('prikaz_o_zone_podtop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deyatelnost.prikazozonepodtop')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Добавить список файлов',
            },
        ),
        migrations.CreateModel(
            name='FilePrikazOZonePodtop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название файла')),
                ('file', models.FileField(blank=True, upload_to='deyatelnost/prikazy_o_zone_podtop/files', verbose_name='Файл')),
                ('list_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deyatelnost.listfileprikazozonepodtop', verbose_name='Пояснение к файлу')),
                ('picture_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.picturefile', verbose_name='Расширение файла')),
                ('prikaz_o_zone_podtop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deyatelnost.prikazozonepodtop')),
            ],
            options={
                'verbose_name': 'Файл',
            },
        ),
    ]
