# Generated by Django 4.0.5 on 2022-08-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deyatelnost', '0014_listfileprikazozonepodtop_fileprikazozonepodtop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentdeyatelnost',
            options={'ordering': ['-date_change'], 'verbose_name': 'Контент', 'verbose_name_plural': '1. Добавить Контент'},
        ),
        migrations.AlterModelOptions(
            name='prikazozonepodtop',
            options={'verbose_name': 'Приказы об определении границы зоны затопления', 'verbose_name_plural': '3. Приказы об определении границы зоны затопления'},
        ),
        migrations.AlterModelOptions(
            name='vodhoz',
            options={'ordering': ['-date_created'], 'verbose_name': 'Водохозяйственныую обстановку', 'verbose_name_plural': '2. Водохозяйственная обстановка'},
        ),
    ]
