# Generated by Django 4.0.5 on 2022-08-05 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0091_alter_content_options'),
        ('okazanie_gosuslug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentOkazanieGosuslug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('content_okazanie_gosuslug', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('mode_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.modepage', verbose_name='Вид контекста')),
                ('un_menu_norm_akt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okazanie_gosuslug.unmenuokazaniegosuslug', verbose_name='Подпункт меню')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': '1. Добавить Контент',
                'ordering': ['-date_change'],
            },
        ),
    ]
