# Generated by Django 4.0.5 on 2022-08-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okazanie_gosuslug', '0002_contentokazaniegosuslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentokazaniegosuslug',
            old_name='un_menu_norm_akt',
            new_name='un_menu_okazanie_gosuslug',
        ),
    ]
