# Generated by Django 4.0.5 on 2022-08-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0091_alter_content_options'),
        ('okazanie_gosuslug', '0003_rename_un_menu_norm_akt_contentokazaniegosuslug_un_menu_okazanie_gosuslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFileOkazanieGosuslug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст (пояснение к файлу)')),
                ('content_okazanie_gosuslug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okazanie_gosuslug.contentokazaniegosuslug')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Добавить список файлов',
            },
        ),
        migrations.CreateModel(
            name='FileOkazanieGosuslug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название файла')),
                ('file', models.FileField(blank=True, upload_to='okazanie_gosuslug/files', verbose_name='Файл')),
                ('content_okazanie_gosuslug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okazanie_gosuslug.contentokazaniegosuslug')),
                ('list_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okazanie_gosuslug.listfileokazaniegosuslug', verbose_name='Пояснение к файлу')),
                ('picture_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.picturefile', verbose_name='Расширение файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Добавить файлы',
            },
        ),
    ]
