# Generated by Django 4.0.5 on 2022-07-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReglamentyStandartyGosUslug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title', models.TextField(verbose_name='Текст заголовка')),
                ('file_pdf', models.FileField(upload_to='normativ_document/admin_reglamenty_standarty_gos_uslug', verbose_name='Файл PDF')),
                ('file_doc', models.FileField(upload_to='normativ_document/admin_reglamenty_standarty_gos_uslug', verbose_name='Файл WORD')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Услуги по утверждению нормативов',
                'verbose_name_plural': '2. Предоставление государственной услуги по утверждению нормативов допустимых сбросов веществ в водные объекты для водопользователей',
            },
        ),
    ]
