# Generated by Django 4.0.5 on 2022-07-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0004_adminreglamentystandartygosuslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreglamentystandartygosuslug',
            name='file_doc',
            field=models.FileField(blank=True, upload_to='normativ_document/admin_reglamenty_standarty_gos_uslug', verbose_name='Файл WORD'),
        ),
        migrations.AlterField(
            model_name='adminreglamentystandartygosuslug',
            name='file_pdf',
            field=models.FileField(blank=True, upload_to='normativ_document/admin_reglamenty_standarty_gos_uslug', verbose_name='Файл PDF'),
        ),
    ]
