# Generated by Django 4.0.5 on 2022-07-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0005_alter_adminreglamentystandartygosuslug_file_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegStandart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title', models.TextField(verbose_name='Текст заголовка')),
                ('links', models.CharField(blank=True, max_length=255, verbose_name='Внешняя ссылка но документ')),
                ('file_pdf', models.FileField(blank=True, upload_to='normativ_document/admin_reglamenty_standarty_gos_uslug', verbose_name='Файл PDF')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Регламент',
                'verbose_name_plural': '2.1. Административные регламенты, стандарты государственных услуг',
            },
        ),
    ]
