# Generated by Django 4.0.5 on 2022-07-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0006_adminregstandart2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminreglamentystandartygosuslug',
            options={'verbose_name': 'Услуги по утверждению нормативов', 'verbose_name_plural': '2. Предоставление государственной услуги по утверждению нормативов допустимых сбросов веществ в водные объекты для водопользователей ("Административные регламенты, стандарты государственных услуг")'},
        ),
        migrations.AlterModelOptions(
            name='adminregstandart2',
            options={'verbose_name': 'Регламент', 'verbose_name_plural': '2.1. Административные регламенты, стандарты государственных услуг ("Административные регламенты, стандарты государственных услуг")'},
        ),
    ]
