# Generated by Django 4.0.5 on 2022-07-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0007_alter_adminreglamentystandartygosuslug_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UstanovFormy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title', models.TextField(verbose_name='Текст к документу')),
                ('file_pdf', models.FileField(blank=True, upload_to='normativ_document/ustanovlennye_formy_obraaheniy', verbose_name='Файл PDF')),
                ('file_doc', models.FileField(blank=True, upload_to='normativ_document/ustanovlennye_formy_obraaheniy', verbose_name='Файл Word')),
                ('file_exel', models.FileField(blank=True, upload_to='normativ_document/ustanovlennye_formy_obraaheniy', verbose_name='Файл Exel')),
                ('file_zip', models.FileField(blank=True, upload_to='normativ_document/ustanovlennye_formy_obraaheniy', verbose_name='Файл ZIP')),
                ('links', models.CharField(blank=True, max_length=255, verbose_name='Внешняя ссылка но документ')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Регламент',
                'verbose_name_plural': '3. Установленные формы обращений, заявлений и иных документов',
            },
        ),
    ]
