# Generated by Django 4.0.5 on 2022-07-17 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0008_ustanovformy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminreglamentystandartygosuslug',
            options={'ordering': ['-date_created'], 'verbose_name': 'Услуги по утверждению нормативов', 'verbose_name_plural': '2. Предоставление государственной услуги по утверждению нормативов допустимых сбросов веществ в водные объекты для водопользователей ("Административные регламенты, стандарты государственных услуг")'},
        ),
        migrations.AlterModelOptions(
            name='adminregstandart2',
            options={'ordering': ['-date_created'], 'verbose_name': 'Регламент', 'verbose_name_plural': '2.1. Административные регламенты, стандарты государственных услуг ("Административные регламенты, стандарты государственных услуг")'},
        ),
        migrations.AlterModelOptions(
            name='normaktrosvod',
            options={'ordering': ['-date_created'], 'verbose_name': 'Текст статьи', 'verbose_name_plural': '1. Нормативные правовые акты, изданные Федеральным агентством водных ресурсов'},
        ),
        migrations.AlterModelOptions(
            name='ustanovformy',
            options={'ordering': ['-date_created'], 'verbose_name': 'Документ', 'verbose_name_plural': '3. Установленные формы обращений, заявлений и иных документов'},
        ),
        migrations.RemoveField(
            model_name='ustanovformy',
            name='file_exel',
        ),
        migrations.CreateModel(
            name='ExelUstanovForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_exel', models.FileField(blank=True, upload_to='normativ_document/ustanovlennye_formy_obraaheniy', verbose_name='Файл Exel')),
                ('ustanov_formy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normativ_document.ustanovformy')),
            ],
        ),
    ]
