# Generated by Django 4.0.5 on 2022-07-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0009_alter_adminreglamentystandartygosuslug_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExelUstanovForm',
        ),
        migrations.DeleteModel(
            name='UstanovFormy',
        ),
    ]
