# Generated by Django 4.0.5 on 2022-07-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0012_exelustanovform_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exelustanovform',
            options={'verbose_name': 'Exel', 'verbose_name_plural': 'Добавить Exel документ'},
        ),
    ]
