# Generated by Django 4.0.5 on 2022-07-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0013_alter_exelustanovform_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminReglamentyStandartyGosUslug',
        ),
        migrations.DeleteModel(
            name='AdminRegStandart2',
        ),
        migrations.RemoveField(
            model_name='exelustanovform',
            name='ustanov_formy',
        ),
        migrations.DeleteModel(
            name='NormAktRosvod',
        ),
        migrations.DeleteModel(
            name='ExelUstanovForm',
        ),
        migrations.DeleteModel(
            name='UstanovFormy',
        ),
    ]
