# Generated by Django 4.0.5 on 2022-07-22 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enisey_bvu', '0085_remove_content_unmenu_content_un_menu_enbv'),
        ('normativ_document', '0014_delete_adminreglamentystandartygosuslug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNormAkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('mode_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.modepage', verbose_name='Вид контекста')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Добавить Контент',
                'ordering': ['-date_change'],
            },
        ),
        migrations.CreateModel(
            name='UnMenuNormAkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ListFileNormAkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст (пояснение к файлу)')),
                ('content_norm_akt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normativ_document.contentnormakt')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Добавить список файлов',
            },
        ),
        migrations.CreateModel(
            name='FileNormAkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='enisey_bvu/files', verbose_name='Файл')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normativ_document.contentnormakt')),
                ('list_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normativ_document.listfilenormakt', verbose_name='Пояснение к файлу')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Добавить файлы',
            },
        ),
        migrations.AddField(
            model_name='contentnormakt',
            name='un_menu_norm_akt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normativ_document.unmenunormakt', verbose_name='Подпункт меню'),
        ),
    ]
