# Generated by Django 4.0.5 on 2022-07-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0015_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenormakt',
            name='file',
            field=models.FileField(blank=True, upload_to='normativ_document/files', verbose_name='Файл'),
        ),
    ]
