# Generated by Django 4.0.5 on 2022-07-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0017_filenormakt_name_filenormakt_picture_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filenormakt',
            old_name='content',
            new_name='content_norm_akt',
        ),
    ]
