# Generated by Django 4.0.5 on 2022-07-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normativ_document', '0018_rename_content_filenormakt_content_norm_akt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentnormakt',
            options={'ordering': ['un_menu_norm_akt'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Добавить Контент'},
        ),
    ]
