# Generated by Django 4.0.5 on 2022-08-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadr_provision', '0002_kadrprovision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kadrprovision',
            name='mode_page',
        ),
    ]
