# Generated by Django 4.0.5 on 2022-08-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadr_provision', '0005_kadrprovision_mode_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kadrprovision',
            options={'ordering': ['-date_change'], 'verbose_name': 'Контент', 'verbose_name_plural': '1. Добавить Контент'},
        ),
    ]
