# Generated by Django 4.0.5 on 2022-06-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormativAkt',
        ),
    ]
