# Generated by Django 4.0.5 on 2022-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polnomochiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_polnomochiya', models.TextField(verbose_name='Полномочия')),
            ],
            options={
                'verbose_name': 'Пункт полномочий',
                'verbose_name_plural': 'Полномочия',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='functionuprav',
            options={'ordering': ['id'], 'verbose_name': 'Основную функцию Управления', 'verbose_name_plural': 'Основные функции Управления'},
        ),
    ]
