# Generated by Django 4.0.5 on 2022-07-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0005_normaktfunction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaktfunction',
            name='url_doc',
        ),
    ]
