# Generated by Django 4.0.5 on 2022-07-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0009_organization_worker_phoneworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneworker',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='phoneworker',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='PhoneWorker',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
