# Generated by Django 4.0.5 on 2022-07-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0011_worker_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организацию', 'verbose_name_plural': 'Организация'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='worker',
        ),
    ]
