# Generated by Django 4.0.5 on 2022-07-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0012_alter_organization_options_alter_worker_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
