# Generated by Django 4.0.5 on 2022-07-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0013_delete_organization_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование организации')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('address_cor', models.TextField(verbose_name='Адрес для корреспонденции')),
                ('mode', models.CharField(max_length=300, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Организацию',
                'verbose_name_plural': 'Организация',
            },
        ),
        migrations.AlterModelOptions(
            name='functionuprav',
            options={'ordering': ['id'], 'verbose_name': 'Основную функцию Управления', 'verbose_name_plural': '1.  Основные функции Управления  "(Функции и полномочия Енисейского БВУ)"'},
        ),
        migrations.AlterModelOptions(
            name='normaktfunction',
            options={'ordering': ['id'], 'verbose_name': 'Документ', 'verbose_name_plural': '2. Нормативные акты, определяющие полномочия, задачи и функции'},
        ),
        migrations.AlterModelOptions(
            name='polnomochiya',
            options={'ordering': ['id'], 'verbose_name': 'Пункт полномочий', 'verbose_name_plural': '1.1  Полномочия "(Функции и полномочия Енисейского БВУ)"'},
        ),
    ]
