# Generated by Django 4.0.5 on 2022-07-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0015_alter_organization_address_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mode',
            field=models.CharField(blank=True, max_length=300, verbose_name='Режим работы'),
        ),
    ]
