# Generated by Django 4.0.5 on 2022-07-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0016_alter_organization_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Телефон организации')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.organization')),
            ],
        ),
    ]
