# Generated by Django 4.0.5 on 2022-07-08 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0018_organization_email_organization_fax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сотрудника',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='PhoneWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Телефон сотрудника')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.worker')),
            ],
        ),
    ]
