# Generated by Django 4.0.5 on 2022-07-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0019_worker_phoneworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sector',
            field=models.CharField(blank=True, max_length=355, verbose_name='Отдел'),
        ),
    ]
