# Generated by Django 4.0.5 on 2022-07-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0020_organization_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='sector',
        ),
        migrations.CreateModel(
            name='SectorOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355, verbose_name='Отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.organization')),
            ],
        ),
    ]
