# Generated by Django 4.0.5 on 2022-07-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0022_worker_sector_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='sector_organization',
        ),
    ]
