# Generated by Django 4.0.5 on 2022-07-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0023_remove_worker_sector_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='organization',
        ),
        migrations.AddField(
            model_name='worker',
            name='sector_organization',
            field=models.ManyToManyField(to='enisey_bvu.organization'),
        ),
    ]
