# Generated by Django 4.0.5 on 2022-07-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0024_remove_worker_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='sector_organization',
            new_name='organization',
        ),
    ]
