# Generated by Django 4.0.5 on 2022-07-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0025_rename_sector_organization_worker_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='organization',
        ),
    ]
