# Generated by Django 4.0.5 on 2022-07-08 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0028_alter_worker_sector_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='sector_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.sectororganization', verbose_name='Отдел'),
        ),
    ]
