# Generated by Django 4.0.5 on 2022-07-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0031_alter_worker_sector_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uchrezhdeniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название учреждения')),
                ('worker_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('site', models.CharField(max_length=255, verbose_name='Сайт')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Подведомственное учреждение',
                'verbose_name_plural': '4. Подведомственные учреждения',
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организацию', 'verbose_name_plural': '3.1 Организация ("Структура управления")'},
        ),
        migrations.AlterModelOptions(
            name='phoneorganization',
            options={'verbose_name': 'Телефоны организации', 'verbose_name_plural': 'Телефон организации'},
        ),
        migrations.AlterModelOptions(
            name='phoneworker',
            options={'verbose_name': 'Телефон сотрудника', 'verbose_name_plural': 'Телефоны сотрудника'},
        ),
        migrations.AlterModelOptions(
            name='sectororganization',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Сотрудника', 'verbose_name_plural': '3.2 Сотрудники ("Структура управления")'},
        ),
        migrations.CreateModel(
            name='PhoneUchrezhdeniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(verbose_name='Адрес Подведомственного учреждения')),
                ('uchrezhdenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.uchrezhdeniya')),
            ],
            options={
                'verbose_name': 'Телефон Подведомственного учреждения',
                'verbose_name_plural': 'Телефоны Подведомственного учреждения',
            },
        ),
        migrations.CreateModel(
            name='AddressUchrezhdeniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес Подведомственного учреждения')),
                ('uchrezhdenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.uchrezhdeniya')),
            ],
            options={
                'verbose_name': 'Адрес Подведомственного учреждения',
                'verbose_name_plural': 'Адрес Подведомственного учреждения',
            },
        ),
    ]
