# Generated by Django 4.0.5 on 2022-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0032_uchrezhdeniya_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneuchrezhdeniya',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон Подведомственного учреждения'),
        ),
    ]
