# Generated by Django 4.0.5 on 2022-07-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0033_alter_phoneuchrezhdeniya_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneuchrezhdeniya',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.addressuchrezhdeniya'),
            preserve_default=False,
        ),
    ]
