# Generated by Django 4.0.5 on 2022-07-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0034_phoneuchrezhdeniya_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uchrezhdeniya',
            name='site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сайт'),
        ),
    ]
