# Generated by Django 4.0.5 on 2022-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0035_alter_uchrezhdeniya_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoZakupki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
