# Generated by Django 4.0.5 on 2022-07-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0037_planproverok_alter_infozakupki_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planproverok',
            options={'ordering': ['-title'], 'verbose_name': 'План проверок', 'verbose_name_plural': '6. План проверок, результаты проверок'},
        ),
    ]
