# Generated by Django 4.0.5 on 2022-07-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0038_alter_planproverok_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planproverok',
            options={'ordering': ['id'], 'verbose_name': 'План проверок', 'verbose_name_plural': '6. План проверок, результаты проверок'},
        ),
    ]
