# Generated by Django 4.0.5 on 2022-07-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0039_alter_planproverok_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficialVystup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('file_pdf', models.FileField(blank=True, upload_to='enisey_enbvu/oficial-vystupleniya_pdf', verbose_name='Файл пдф')),
                ('file', models.FileField(blank=True, upload_to='enisey_enbvu/oficial-vystupleniya_file', verbose_name='Файл')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Официальных выступление или заявление',
                'verbose_name_plural': '7.  Официальные выступления и заявления',
            },
        ),
    ]
