# Generated by Django 4.0.5 on 2022-07-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0040_oficialvystup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficialvystup',
            name='file',
        ),
    ]
