# Generated by Django 4.0.5 on 2022-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0041_remove_oficialvystup_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvedeniyaSmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Сведения о финансировании (отсутсвии финансирования) средств массовой информации',
                'verbose_name_plural': '8.  Сведения о финансировании (отсутсвии финансирования) средств массовой информации',
            },
        ),
        migrations.AlterModelOptions(
            name='oficialvystup',
            options={'verbose_name': 'Официальное выступление или заявление', 'verbose_name_plural': '7.  Официальные выступления и заявления'},
        ),
    ]
