# Generated by Django 4.0.5 on 2022-07-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0043_perechniinfosistembvu_alter_infozakupki_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perechniinfosistembvu',
            options={'verbose_name': 'Текст', 'verbose_name_plural': '5. Перечни информационных систем, банков данных, реестров, регистров, находящихся в ведении Енисейского БВУ'},
        ),
    ]
