# Generated by Django 4.0.5 on 2022-07-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0044_alter_perechniinfosistembvu_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunctionUprav',
        ),
        migrations.DeleteModel(
            name='Polnomochiya',
        ),
    ]
