# Generated by Django 4.0.5 on 2022-07-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0046_functionuprav_polnomochiya'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionuprav',
            options={'ordering': ['-date_created'], 'verbose_name': 'Основную функцию Управления', 'verbose_name_plural': '1.  Основные функции Управления  "(Функции и полномочия Енисейского БВУ)"'},
        ),
        migrations.AlterField(
            model_name='functionuprav',
            name='date_chenge',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='polnomochiya',
            name='date_chenge',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
