# Generated by Django 4.0.5 on 2022-07-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0047_alter_functionuprav_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormAktFunction',
        ),
        migrations.AlterModelOptions(
            name='functionuprav',
            options={'ordering': ['date_created'], 'verbose_name': 'Основную функцию Управления', 'verbose_name_plural': '1.  Основные функции Управления  "(Функции и полномочия Енисейского БВУ)"'},
        ),
        migrations.AlterModelOptions(
            name='polnomochiya',
            options={'ordering': ['date_created'], 'verbose_name': 'Пункт полномочий', 'verbose_name_plural': '1.1  Полномочия "(Функции и полномочия Енисейского БВУ)"'},
        ),
        migrations.AlterField(
            model_name='oficialvystup',
            name='file_pdf',
            field=models.FileField(blank=True, upload_to='enisey_bvu/oficial-vystupleniya_pdf', verbose_name='Файл пдф'),
        ),
    ]
