# Generated by Django 4.0.5 on 2022-07-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0048_delete_normaktfunction_alter_functionuprav_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormAktFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название документа')),
                ('file_pdf', models.FileField(blank=True, upload_to='enisey_bvu/normativnye_akty_function', verbose_name='Документ')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': '2. Нормативные акты, определяющие полномочия, задачи и функции',
                'ordering': ['id'],
            },
        ),
    ]
