# Generated by Django 4.0.5 on 2022-07-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0051_organization_sectororganization_worker_phoneworker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneuchrezhdeniya',
            name='address',
        ),
        migrations.RemoveField(
            model_name='phoneuchrezhdeniya',
            name='uchrezhdenie',
        ),
        migrations.DeleteModel(
            name='AddressUchrezhdeniya',
        ),
        migrations.DeleteModel(
            name='PhoneUchrezhdeniya',
        ),
        migrations.DeleteModel(
            name='Uchrezhdeniya',
        ),
    ]
