# Generated by Django 4.0.5 on 2022-07-14 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0052_remove_phoneuchrezhdeniya_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressUchrezhdeniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес Подведомственного учреждения')),
            ],
            options={
                'verbose_name': 'Адрес Подведомственного учреждения',
                'verbose_name_plural': 'Адрес Подведомственного учреждения',
            },
        ),
        migrations.CreateModel(
            name='Uchrezhdeniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название учреждения')),
                ('worker_name', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('site', models.CharField(blank=True, max_length=255, verbose_name='Сайт')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Подведомственное учреждение',
                'verbose_name_plural': '4. Подведомственные учреждения',
            },
        ),
        migrations.CreateModel(
            name='PhoneUchrezhdeniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон Подведомственного учреждения')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.addressuchrezhdeniya')),
                ('uchrezhdenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.uchrezhdeniya')),
            ],
            options={
                'verbose_name': 'Телефон Подведомственного учреждения',
                'verbose_name_plural': 'Телефоны Подведомственного учреждения',
            },
        ),
        migrations.AddField(
            model_name='addressuchrezhdeniya',
            name='uchrezhdenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.uchrezhdeniya'),
        ),
    ]
