# Generated by Django 4.0.5 on 2022-07-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0056_delete_infozakupki'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoZakupki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Статью закупки',
                'verbose_name_plural': '6. Информация об осуществлении закупок товаров, работ, услуг для государственных нужд',
            },
        ),
    ]
