# Generated by Django 4.0.5 on 2022-07-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0059_planproverok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OficialVystup',
        ),
        migrations.AlterModelOptions(
            name='planproverok',
            options={'ordering': ['-date_created'], 'verbose_name': 'План проверок', 'verbose_name_plural': '7. План проверок, результаты проверок'},
        ),
    ]
