# Generated by Django 4.0.5 on 2022-07-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0060_delete_oficialvystup_alter_planproverok_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficialVystup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('file_pdf', models.FileField(blank=True, upload_to='enisey_bvu/oficial-vystupleniya_pdf', verbose_name='Файл пдф')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Официальное выступление или заявление',
                'verbose_name_plural': '8.  Официальные выступления и заявления',
            },
        ),
    ]
