# Generated by Django 4.0.5 on 2022-07-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0061_oficialvystup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SvedeniyaSmi',
        ),
    ]
