# Generated by Django 4.0.5 on 2022-07-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0062_delete_svedeniyasmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvedeniyaSmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Сведения о финансировании (отсутсвии финансирования) средств массовой информации',
                'verbose_name_plural': '9.  Сведения о финансировании (отсутсвии финансирования) средств массовой информации',
            },
        ),
    ]
