# Generated by Django 4.0.5 on 2022-07-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0063_svedeniyasmi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организацию', 'verbose_name_plural': '3. Организация ("Структура управления")'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Сотрудника', 'verbose_name_plural': '3.1 Сотрудники ("Структура управления")'},
        ),
    ]
