# Generated by Django 4.0.5 on 2022-07-18 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index_enbvu', '0040_alter_mirvodyimage_options_alter_newsfilepdf_options_and_more'),
        ('enisey_bvu', '0065_remove_addressuchrezhdeniya_uchrezhdenie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок страницы')),
                ('un_title', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок (раздел на странице)')),
                ('content', models.TextField(verbose_name='Текст страницы')),
                ('date_created', models.DateTimeField(verbose_name='Дата добавления')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('unMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_enbvu.unmenu')),
            ],
        ),
    ]
