# Generated by Django 4.0.5 on 2022-07-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0066_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
        ),
        migrations.RemoveField(
            model_name='textpage',
            name='un_title',
        ),
    ]
