# Generated by Django 4.0.5 on 2022-07-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0068_content_file_title_delete_phone_delete_textpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
