# Generated by Django 4.0.5 on 2022-07-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0071_modepage_alter_content_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='mode_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.modepage', verbose_name='Вид контекста'),
        ),
    ]
