# Generated by Django 4.0.5 on 2022-07-19 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0072_alter_content_mode_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_pdf',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='enisey_bvu/files', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='ListFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст (пояснение к файлу)')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.content')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Добавить файлы',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='list_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.listfile'),
            preserve_default=False,
        ),
    ]
