# Generated by Django 4.0.5 on 2022-07-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0073_alter_file_options_remove_file_file_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст страницы'),
        ),
    ]
