# Generated by Django 4.0.5 on 2022-07-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0074_alter_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfile',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст (пояснение к файлу)'),
        ),
    ]
