# Generated by Django 4.0.5 on 2022-07-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0076_alter_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(blank=True, default='-', verbose_name='Текст страницы'),
        ),
    ]
