# Generated by Django 4.0.5 on 2022-07-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0078_organization_sectororganization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneorganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='phoneworker',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='sectororganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='sector_organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='PhoneOrganization',
        ),
        migrations.DeleteModel(
            name='PhoneWorker',
        ),
        migrations.DeleteModel(
            name='SectorOrganization',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
