# Generated by Django 4.0.5 on 2022-07-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0079_remove_phoneorganization_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNameFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название приложения')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='mode_page',
        ),
    ]
