# Generated by Django 4.0.5 on 2022-07-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0080_appnamefilter_remove_content_mode_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mode_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.modepage', verbose_name='Вид контекста'),
            preserve_default=False,
        ),
    ]
