# Generated by Django 4.0.5 on 2022-07-20 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0081_content_mode_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='app_name_filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.appnamefilter', verbose_name='Название приложения'),
            preserve_default=False,
        ),
    ]
