# Generated by Django 4.0.5 on 2022-07-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0082_content_app_name_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnMenuENBVU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('url', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='app_name_filter',
        ),
        migrations.DeleteModel(
            name='AppNameFilter',
        ),
    ]
