# Generated by Django 4.0.5 on 2022-07-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0083_unmenuenbvu_remove_content_app_name_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unmenuenbvu',
            name='url',
        ),
    ]
