# Generated by Django 4.0.5 on 2022-07-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0084_remove_unmenuenbvu_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='unMenu',
        ),
        migrations.AddField(
            model_name='content',
            name='un_menu_enbv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.unmenuenbvu', verbose_name='Подпункт меню'),
            preserve_default=False,
        ),
    ]
