# Generated by Django 4.0.5 on 2022-07-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0085_remove_content_unmenu_content_un_menu_enbv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Расширение файла')),
            ],
        ),
    ]
