# Generated by Django 4.0.5 on 2022-07-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0087_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='picture_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enisey_bvu.picturefile', verbose_name='Расширение файла'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название файла'),
        ),
    ]
