# Generated by Django 4.0.5 on 2022-07-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0088_file_picture_file_alter_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['un_menu_enbv'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Добавить Контент'},
        ),
    ]
