# Generated by Django 4.0.5 on 2022-08-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enisey_bvu', '0090_alter_content_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-date_change'], 'verbose_name': 'Контент', 'verbose_name_plural': '1. Добавить Контент'},
        ),
    ]
